[project]
name = "sayso-server"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "AmperesAI", email = "moorthyv@amperes.pro" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pipecat-ai[deepgram,gradium,hume,local-smart-turn,mlx-whisper,openai,runner,sambanova,silero,webrtc,whisper]>=1.11.0",
    "python-dotenv>=1.2.3",
    "websockets>=17.1",
]

[project.scripts]
sayso-server = "sayso_server:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
